server.port=9090
spring.application.name=dynamicworkflow
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dynamicworkflow}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.username=${DB_USERNAME:postgres}
dynamic.workflow.temporal-address=localhost:7233
dynamic.workflow.temporal-namespace=default
dynamic.workflow.task-queue=DYNAMIC_WORKFLOW_QUEUE
